#!/usr/bin/env bash
#    %     10  20  30  40  50  60  70  80  90
icons=("" "" "" "" "" "" "" "" "" "")
num_icons=$(bc <<<"100 / ${#icons[@]}")

geticon() {
  level=$(awk -v n="$CAPACITY" -v c="$num_icons" 'BEGIN{print int((n-1)/c)}')
  if [[ "$level" -lt 0 ]]; then
    level=0
  fi
  echo "${icons[$level]}"
}

status() {
  if [ "$STATE" = "Charging" ]; then
    echo -n "charging"

    if [ "$RATE" -gt 0 ]; then
      echo ", $(gettime) left"
    else
      echo ""
    fi
  elif [ "$STATE" = "Discharging" ]; then
    echo "$(gettime)h left"
  else
    echo "fully charged"
  fi
}

class() {
  if [ "$CAPACITY" -le 10 ]; then
    echo 'battery-critical'
  elif [ "$CAPACITY" -le 20 ]; then
    echo 'battery-low'
  fi
}

wattage() {
  microwatts=1000000
  echo "$(bc -l <<<"scale=1; $RATE / $microwatts") W"
}

gettime() {
  FULL=$(cat /sys/class/power_supply/BAT1/energy_full)
  NOW=$(cat /sys/class/power_supply/BAT1/energy_now)

  if [ "$RATE" -gt 0 ]; then
    if [ "$STATE" = "Discharging" ]; then
      EX="$NOW / $RATE"
    else
      EX="($FULL - $NOW) / $RATE"
    fi
    date -u -d@"$(bc -l <<<"$EX * 3600")" +%H:%M
  fi
}

while [ -d "/sys/class/power_supply/BAT1" ]; do
  RATE=$(cat /sys/class/power_supply/BAT1/power_now)
  CAPACITY=$(cat /sys/class/power_supply/BAT1/capacity)
  STATE=$(cat /sys/class/power_supply/BAT1/status)

  echo '{ "icon": "'"$(geticon)"'", "percent": "'"$CAPACITY"'", "wattage": "'"$(wattage)"'", "status": "'"$(status)"'", "class": "'"$(class)"'" }'
  sleep 3
done
