#!/usr/bin/env python3

import json
import socket
import time

HOST = "127.0.0.1"  # Standard loopback interface address (localhost)
PORT = 36413  # Port to listen on (non-privileged ports are > 1023)

print("cm", flush=True)
time.sleep(2)
with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
    s.connect((HOST, PORT))
    while True:
        data = s.recv(1024)
        output = json.loads(data)["LayerChange"]["new"]
        match output:
            case "colemakdh":
                output = "cm"
            case "qwerty":
                output = "qw"
            case "navigation":
                output = "nv"
            case _:
                output = "?"
        print(output, flush=True)
