#!/usr/bin/env python3

import json
import socket
import time

HOST = "127.0.0.1"  # Standard loopback interface address (localhost)
PORT = 36413  # Port to listen on (non-privileged ports are > 1023)

print(json.dumps({"full": "colemakdh", "shorthand": "cm"}), flush=True)
time.sleep(2)

with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
    s.connect((HOST, PORT))
    while True:
        data = s.recv(1024)
        full_name = json.loads(data)["LayerChange"]["new"]

        shorthand_map = {"colemakdh": "cm", "qwerty": "qw", "navigation": "nv"}

        shorthand = shorthand_map.get(full_name, "?")

        print(json.dumps({"full": full_name, "shorthand": shorthand}), flush=True)
