#!/usr/bin/env bash
hyprctl activewindow -j | jq --raw-output .title
socat -u UNIX-CONNECT:/tmp/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock - | stdbuf -o0 grep '^activewindow>>' | stdbuf -o0 awk -F '>>|,' '{print $2 "::" $3}' | stdbuf -o0 cut -c1-35 | stdbuf -o0 sed 's/[ \t]*$//' 
