#!/usr/bin/env bash
icon="";
echo "$icon en"
socat -u UNIX-CONNECT:/tmp/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock - | stdbuf -o0 grep '^activelayout>>' | stdbuf -o0 awk -F '>>|,' '{print $3}' | {
  while read -r language; do
    if [ "$language" = "English (US)" ]; then
      echo "$icon en";
    elif [ "$language" = "Swedish" ]; then
      echo "$icon sv";
    fi
  done
}
