#!/bin/sh

# TODO: Refactor into a lua/python script.

# This is the example configuration file for river.
#
# If you wish to edit this, you will probably want to copy it to
# $XDG_CONFIG_HOME/river/init or $HOME/.config/river/init first.
#
# See the river(1), riverctl(1), and rivertile(1) man pages for complete
# documentation.

# Note: the "Super" modifier is also known as Logo, GUI, Windows, Mod4, etc.

# https://github.com/swaywm/sway/wiki#gtk-applications-take-20-seconds-to-start
riverctl spawn "systemctl --user import-environment"

# Input configuration.
riverctl input 1739:52656:PNP0C50:00_06CB:CDB0_Touchpad tap enabled

# Terminal emulator.
riverctl map normal Super Return spawn "kitty"

# Application launcher.
riverctl map normal Super D spawn "rofi -show drun"

# Useful applications.
riverctl map normal Super I spawn "emacsclient -nc -a 'emacs'"
riverctl map normal Super B spawn "librewolf"
riverctl map normal Super S spawn "kitty spt"
riverctl map normal Super Y spawn "freetube"

# Screenshotting utilities.
riverctl map normal Super+Shift O spawn "grim - | wl-copy"
riverctl map normal Super+Shift A spawn 'grim -g "$(slurp)" - | wl-copy'

# Super+W to close the focused view.
riverctl map normal Super W close

# Super+Shift+E to exit river.
riverctl map normal Super+Shift E exit

# Super+J and Super+K to focus the next/previous view in the layout stack.
riverctl map normal Super J focus-view next
riverctl map normal Super K focus-view previous

# Super+Shift+J and Super+Shift+K to swap the focused view with the next/previous.
# view in the layout stack
riverctl map normal Super+Shift J swap next
riverctl map normal Super+Shift K swap previous

# Super+Period and Super+Comma to focus the next/previous output.
riverctl map normal Super Period focus-output next
riverctl map normal Super Comma focus-output previous

# Super+Shift+{Period,Comma} to send the focused view to the next/previous output.
riverctl map normal Super+Shift Period send-to-output next
riverctl map normal Super+Shift Comma send-to-output previous

# Super+Shift+Return to bump the focused view to the top of the layout stack.
riverctl map normal Super+Shift Return zoom

# Super+H and Super+L to decrease/increase the main ratio of rivertile(1).
riverctl map normal Super H send-layout-cmd rivercarro "main-ratio -0.05"
riverctl map normal Super L send-layout-cmd rivercarro "main-ratio +0.05"

# Super+Shift+H and Super+Shift+L to increment/decrement the main count of rivertile(1).
riverctl map normal Super+Shift H send-layout-cmd rivercarro "main-count +1"
riverctl map normal Super+Shift L send-layout-cmd rivercarro "main-count -1"

# Super+Alt+{H,J,K,L} to move views.
riverctl map normal Super+Alt H move left 100
riverctl map normal Super+Alt J move down 100
riverctl map normal Super+Alt K move up 100
riverctl map normal Super+Alt L move right 100

# Super+Alt+Control+{H,J,K,L} to snap views to screen edges.
riverctl map normal Super+Alt+Control H snap left
riverctl map normal Super+Alt+Control J snap down
riverctl map normal Super+Alt+Control K snap up
riverctl map normal Super+Alt+Control L snap right

# Super+Alt+Shift+{H,J,K,L} to resize views.
riverctl map normal Super+Alt+Shift H resize horizontal -100
riverctl map normal Super+Alt+Shift J resize vertical 100
riverctl map normal Super+Alt+Shift K resize vertical -100
riverctl map normal Super+Alt+Shift L resize horizontal 100

# Super + Left Mouse Button to move views.
riverctl map-pointer normal Super BTN_LEFT move-view

# Super + Right Mouse Button to resize views.
riverctl map-pointer normal Super BTN_RIGHT resize-view

for i in $(seq 1 4)
do
    tags=$((1 << ($i - 1)))

    # Super+[1-9] to focus tag [0-8].
    riverctl map normal Super $i set-focused-tags $tags

    # Super+Shift+[1-9] to tag focused view with tag [0-8].
    riverctl map normal Super+Shift $i set-view-tags $tags

    # Super+Ctrl+[1-9] to toggle focus of tag [0-8].
    riverctl map normal Super+Control $i toggle-focused-tags $tags

    # Super+Shift+Ctrl+[1-9] to toggle tag [0-8] of focused view.
    riverctl map normal Super+Shift+Control $i toggle-view-tags $tags
done

# Super+0 to focus all tags.
# Super+Shift+0 to tag focused view with all tags.
all_tags=$(((1 << 32) - 1))
riverctl map normal Super 0 set-focused-tags $all_tags
riverctl map normal Super+Shift 0 set-view-tags $all_tags

# Focus and send views to previous tags (jumping back and forth).
riverctl map normal Super P focus-previous-tags
riverctl map normal Super+Shift P send-to-previous-tags

# Super+Space to toggle float.
riverctl map normal Super Space toggle-float

# Super+F to toggle fullscreen.
riverctl map normal Super F toggle-fullscreen

# Super+{Up,Right,Down,Left} to change layout orientation.
riverctl map normal Super Up    send-layout-cmd rivercarro "main-location top"
riverctl map normal Super Right send-layout-cmd rivercarro "main-location right"
riverctl map normal Super Down  send-layout-cmd rivercarro "main-location bottom"
riverctl map normal Super Left  send-layout-cmd rivercarro "main-location left"
riverctl map normal Super Slash send-layout-cmd rivercarro "main-location monocle"

# Declare a passthrough mode. This mode has only a single mapping to return to
# normal mode. This makes it useful for testing a nested wayland compositor.
riverctl declare-mode passthrough

# Super+F11 to enter passthrough mode.
riverctl map normal Super F11 enter-mode passthrough

# Super+F11 to return to normal mode.
riverctl map passthrough Super F11 enter-mode normal

# Declare an exit mode. This mode makes it easier to shutdown, reboot and suspend.
riverctl declare-mode exit
riverctl map normal Super X enter-mode exit
riverctl map exit Super X enter-mode normal
riverctl map exit Super Escape enter-mode normal

# Exit commands.
riverctl map exit Super S spawn "systemctl suspend"
riverctl map exit Super P spawn "systemctl poweroff"
riverctl map exit Super R spawn "systemctl reboot"

# Various media key mapping examples for both normal and locked mode which do
# not have a modifier.
for mode in normal locked
do
    # Volume keys.
    riverctl map $mode None XF86AudioMute spawn "pactl set-sink-mute @DEFAULT_SINK@ toggle"
    riverctl map $mode None XF86AudioLowerVolume spawn "pactl set-sink-volume @DEFAULT_SINK@ -5%"
    riverctl map $mode None XF86AudioRaiseVolume spawn "pactl set-sink-volume @DEFAULT_SINK@ +5%"
    riverctl map $mode None XF86AudioMicMute spawn "pactl set-source-mute @DEFAULT_SOURCE@ toggle"

    # Player controls.
    riverctl map $mode None XF86AudioPlay spawn "playerctl play-pause"
    riverctl map $mode None XF86AudioStop spawn "playerctl stop"
    riverctl map $mode None XF86AudioNext spawn "playerctl next"
    riverctl map $mode None XF86AudioPrev spawn "playerctl previous"

    # Screen backlight.
    riverctl map $mode None XF86MonBrightnessUp spawn "brightnessctl set 5%+"
    riverctl map $mode None XF86MonBrightnessDown spawn "brightnessctl set 5%-"
done

# Reload configuration.
riverctl map normal Super R spawn "~/.config/river/init"

# Set background and border color.
riverctl border-color-focused 0xa89984
riverctl border-color-unfocused 0x282828
riverctl border-color-urgent 0xcc241d
riverctl border-width 3

# Set repeat rate.
riverctl set-repeat 50 225

# Focus follows cursor, cursor follows focus.
riverctl focus-follows-cursor normal
riverctl set-cursor-warp on-output-change

# Change background.
riverctl map normal Super+Shift N spawn 'killall -q swaybg; swaybg -i "$(find ~/Pictures/Wallpapers -type f | shuf -n 1)" -m fill'

# Start background services.
riverctl spawn "~/.config/river/autostart.sh"

# Set the default layout generator to be rivertile and start it.
# River will send the process group of the init executable SIGTERM on exit.
riverctl default-layout rivercarro
rivercarro -inner-gaps 8 -outer-gaps 8 -main-location right
